name: flarum

services:
  traefik:
    image: traefik:2.5
    container_name: traefik
    command:
      - "--global.checknewversion=false"
      - "--global.sendanonymoususage=false"
      - "--log=true"
      - "--log.level=INFO"
      - "--entrypoints.http=true"
      - "--entrypoints.http.address=:80"
      - "--entrypoints.http.http.redirections.entrypoint.to=https"
      - "--entrypoints.http.http.redirections.entrypoint.scheme=https"
      - "--entrypoints.https=true"
      - "--entrypoints.https.address=:443"
      - "--certificatesresolvers.letsencrypt"
      - "--certificatesresolvers.letsencrypt.acme.storage=acme.json"
      - "--certificatesresolvers.letsencrypt.acme.email=webmaster@example.com"
      - "--certificatesresolvers.letsencrypt.acme.httpchallenge"
      - "--certificatesresolvers.letsencrypt.acme.httpchallenge.entrypoint=http"
      - "--providers.docker"
      - "--providers.docker.watch=true"
      - "--providers.docker.exposedbydefault=false"
    ports:
      - target: 80
        published: 80
        protocol: tcp
      - target: 443
        published: 443
        protocol: tcp
    volumes:
      - "./acme.json:/acme.json"
      - "/var/run/docker.sock:/var/run/docker.sock"
    restart: always

  db:
    image: mariadb:10
    container_name: flarum_db
    command:
      - "mysqld"
      - "--character-set-server=utf8mb4"
      - "--collation-server=utf8mb4_unicode_ci"
    volumes:
      - "./db:/var/lib/mysql"
    environment:
      - "TZ"
      - "MARIADB_RANDOM_ROOT_PASSWORD=yes"
      - "MYSQL_DATABASE"
      - "MYSQL_USER"
      - "MYSQL_PASSWORD"
    restart: always

  msmtpd:
    image: crazymax/msmtpd:latest
    container_name: flarum_msmtpd
    env_file:
      - "./msmtpd.env"
    environment:
      - "TZ"
    restart: always

  flarum:
    image: crazymax/flarum:latest
    container_name: flarum
    depends_on:
      - db
      - msmtpd
    volumes:
      - "./data:/data"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.flarum.entrypoints=https"
      - "traefik.http.routers.flarum.rule=Host(`flarum.example.com`) && PathPrefix(`/flarum`)"
      - "traefik.http.routers.flarum.tls=true"
      - "traefik.http.routers.flarum.tls.certresolver=letsencrypt"
      - "traefik.http.routers.flarum.tls.domains[0].main=flarum.example.com"
      - "traefik.http.middlewares.flarum.stripprefix.prefixes=/flarum"
      - "traefik.http.middlewares.flarum.stripprefix.forceslash=false"
      - "traefik.http.services.flarum.loadbalancer.server.port=8000"
    environment:
      - "TZ"
      - "PUID"
      - "PGID"
      - "DB_HOST=db"
      - "DB_NAME=${MYSQL_DATABASE}"
      - "DB_USER=${MYSQL_USER}"
      - "DB_PASSWORD=${MYSQL_PASSWORD}"
    env_file:
      - "./flarum.env"
    restart: always
